export const reviewTypes = {
  ADD_REVIEW_START: "ADD_REVIEW_START",
  ADD_REVIEW_SUCCESS: "ADD_REVIEW_SUCCESS",
  ADD_REVIEW_FAILURE: "ADD_REVIEW_FAILURE",
  GET_REVIEW_START: "GET_REVIEW_START",
  GET_REVIEW_SUCCESS: "GET_REVIEW_SUCCESS",
  GET_REVIEW_FAILURE: "GET_REVIEW_FAILURE",
};
