const userTypes = {
  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
  REGISTER_EMAIL_START: "REGISTER_EMAIL_START",
  REGISTER_EMAIL_SUCCESS: "REGISTER_EMAIL_SUCCESS",
  REGISTER_EMAIL_FAILURE: "REGISTER_EMAIL_FAILURE",
  SIGN_IN_WITH_EMAIL: "SIGN_IN_WITH_EMAIL",
  RECOVER_PASSOWRD_START: "RECOVER_PASSOWRD_START",
  RECOVER_PASSOWRD_FAILURE: "RECOVER_PASSOWRD_FAILURE",
  RECOVER_PASSOWRD_SUCCESS: "RECOVER_PASSOWRD_SUCCESS",
  CLEAN_UP: "CLEAN_UP",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
};

export default userTypes;
